/*
 * 公開キャストデータ（scripts/build_data.py が自動生成・手編集禁止）
 * 元データ: data/casts.json（管理画面 or 「ランク更新して」で更新）
 */
window.SHOWCASE = {
  "rank_month": "2026-07",
  "casts": [
    {
      "cast_id": 172,
      "name": "鹿鳴りあ",
      "name_reading": "ロクメリア",
      "rank": "GOLD",
      "catch": "歌とガンダムが大好き、バンビ系VTuber。",
      "intro": "歌とガンダムをこよなく愛するバンビ系VTuber。\n透きとおる歌声と、初めてでもすぐ打ち解けられるトークが持ち味。\nBackStageではGOLDクラスの実力派として、今日も1on1のステージに立つ。",
      "x_url": "https://x.com/69meeeeeee",
      "portrait": "",
      "portraits": [
        "assets/172_KV01.webp",
        "assets/172_KV02.webp"
      ],
      "icon": "assets/172_icon.webp",
      "tags": [
        "歌",
        "ガンダム",
        "アニメ",
        "朝活",
        "はじめてさん歓迎"
      ],
      "specs": [
        {
          "label": "好きなもの",
          "value": "ガンプラ・カラオケ・いちご"
        },
        {
          "label": "活動時間",
          "value": "夜 22:00〜"
        }
      ],
      "youtube_id": "aqz-KE-bpKQ",
      "other_url": "",
      "other_label": "",
      "profile_url": "https://back-stage.onelink.me/7z4p/2n9d4530",
      "birth_month": "8月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 232,
      "name": "水戸わかな",
      "name_reading": "ミトワカナ",
      "rank": "GOLD",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/mitowakana",
      "portrait": "",
      "portraits": [],
      "icon": "assets/232_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 205,
      "name": "三毒ローパ",
      "name_reading": "ミドクローパ",
      "rank": "SILVER",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/MidokuLobha",
      "portrait": "",
      "portraits": [],
      "icon": "assets/205_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "10月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 239,
      "name": "天使ちよむ",
      "name_reading": "テンシチヨム",
      "rank": "SILVER",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/tenshitiyomu",
      "portrait": "",
      "portraits": [],
      "icon": "assets/239_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "10月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 241,
      "name": "玉木瑶",
      "name_reading": "タマキヨウ",
      "rank": "SILVER",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/TamakiYouBS",
      "portrait": "",
      "portraits": [],
      "icon": "assets/241_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "3月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 296,
      "name": "宇田わん",
      "name_reading": "ウタワン",
      "rank": "SILVER",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/uta_wanUo_oU",
      "portrait": "",
      "portraits": [],
      "icon": "assets/296_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "11月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 392,
      "name": "こぐま もる",
      "name_reading": "コグマモル",
      "rank": "SILVER",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/KUMANO_moru",
      "portrait": "",
      "portraits": [],
      "icon": "assets/392_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 407,
      "name": "蔦ヰ田リウ",
      "name_reading": "ツタイダリウ",
      "rank": "SILVER",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/riu_ttid",
      "portrait": "",
      "portraits": [],
      "icon": "assets/407_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "1月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 154,
      "name": "あまち",
      "name_reading": "アマチ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/pochakk666",
      "portrait": "",
      "portraits": [],
      "icon": "assets/154_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "3月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 188,
      "name": "真白ひなた",
      "name_reading": "マシロヒナタ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/hinata_bsc",
      "portrait": "",
      "portraits": [],
      "icon": "assets/188_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "12月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 227,
      "name": "琴葉",
      "name_reading": "コトハ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/hazime0501",
      "portrait": "",
      "portraits": [],
      "icon": "assets/227_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "3月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 236,
      "name": "超絶はおちー",
      "name_reading": "チョウゼツハオチー",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/chouzetu_haochi",
      "portrait": "",
      "portraits": [],
      "icon": "",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "",
      "call_category": ""
    },
    {
      "cast_id": 303,
      "name": "水野ゆか",
      "name_reading": "ミズノユカ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/BackStage_MznYk",
      "portrait": "",
      "portraits": [],
      "icon": "assets/303_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "9月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 313,
      "name": "黒柴えいら",
      "name_reading": "クロシバエイラ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/kuroshibaeila",
      "portrait": "",
      "portraits": [],
      "icon": "assets/313_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "11月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 319,
      "name": "魔法少女ぴょん",
      "name_reading": "マホウショウジョピョン",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/MagicalGirl_PPP",
      "portrait": "",
      "portraits": [],
      "icon": "assets/319_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "12月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 322,
      "name": "如月シノ",
      "name_reading": "キサラギシノ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/Shino_K1219",
      "portrait": "",
      "portraits": [],
      "icon": "assets/322_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "12月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 328,
      "name": "サヤ・グレース",
      "name_reading": "サヤ・グレース",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/SayaGrace38",
      "portrait": "",
      "portraits": [],
      "icon": "assets/328_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 364,
      "name": "音無のあ",
      "name_reading": "オトナシノア",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/Otonashi_Noa",
      "portrait": "",
      "portraits": [],
      "icon": "assets/364_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "10月",
      "call_category": "ドキドキ"
    },
    {
      "cast_id": 388,
      "name": "夢野 てう",
      "name_reading": "Yumeno Teu",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/yumeno_teu",
      "portrait": "",
      "portraits": [],
      "icon": "assets/388_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "8月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 391,
      "name": "小向なのか",
      "name_reading": "コムカイナノカ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/komukai_nanoka",
      "portrait": "",
      "portraits": [],
      "icon": "assets/391_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "2月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 400,
      "name": "桜咲はるね",
      "name_reading": "オウサキハルネ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/ousakiharune",
      "portrait": "",
      "portraits": [],
      "icon": "assets/400_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 414,
      "name": "境内リカ",
      "name_reading": "Keidai Rika",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/tayutauchan",
      "portrait": "",
      "portraits": [],
      "icon": "assets/414_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "11月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 416,
      "name": "にこ",
      "name_reading": "ニコ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "",
      "portrait": "",
      "portraits": [],
      "icon": "assets/416_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "2月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 439,
      "name": "はにゃの",
      "name_reading": "メメンネハニャノ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/hanyano21",
      "portrait": "",
      "portraits": [],
      "icon": "assets/439_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "2月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 446,
      "name": "7_ko（ナナコ）",
      "name_reading": "ナナコ",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/7_ko_s",
      "portrait": "",
      "portraits": [],
      "icon": "assets/446_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "5月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 501,
      "name": "あまタクシー",
      "name_reading": "AMATAXI",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/amataxi4869",
      "portrait": "",
      "portraits": [],
      "icon": "assets/501_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "2月",
      "call_category": "フレンドリー"
    },
    {
      "cast_id": 506,
      "name": "ミラ・エトワール",
      "name_reading": "Mira Etoile",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/mira_etoile_2",
      "portrait": "",
      "portraits": [],
      "icon": "assets/506_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "4月",
      "call_category": "ドリーマー"
    },
    {
      "cast_id": 529,
      "name": "赤絲 こゆび",
      "name_reading": "Akaito Koyubi",
      "rank": "BRONZE",
      "catch": "",
      "intro": "",
      "x_url": "https://x.com/_koito_IRIAM",
      "portrait": "",
      "portraits": [],
      "icon": "assets/529_icon.webp",
      "tags": [],
      "specs": [],
      "youtube_id": "",
      "other_url": "",
      "other_label": "",
      "profile_url": "",
      "birth_month": "3月",
      "call_category": "ドリーマー"
    }
  ]
};
